### Importing libraries

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
dataset = pd.read_csv('Data_Preprocessing.csv')
print(dataset)
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [4]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [5]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


### Taking care of missing data

In [7]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
#creating the object of the SimpleImputer class to replace our missing with the mean
imputer.fit(x[:,1:3])
#we use the fit function to fit the imputer on the data set
x[:,1:3] = imputer.transform(x[:, 1:3])
# using the transform function we are actually replacing the missing values

In [8]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


### Encoding the independent Variables

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [0])],remainder = 'passthrough')
#creating the object for ColumnTransformer with OneHotEncoder for 1st column
x = np.array(ct.fit_transform(x))
# fitting and transform the initial data set and then converting it into a numpy array.

In [10]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [11]:
from sklearn.preprocessing import LabelEncoder
le =LabelEncoder()
y = le.fit_transform(y)

In [12]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


### Splitting the data into train and test set

In [14]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)
#generally we prefer 75:25 ration for train set and test set but since the data here is less i used 80:20 ratio

In [15]:
print(x_train)

[[0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [16]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 50.0 83000.0]]


In [17]:
print(y_train)

[1 1 1 0 1 0 0 1]


In [18]:
print(y_test)

[0 0]


### Feature Scalling

In [19]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)
np.set_printoptions(suppress = True)
print(x)

[[ 1.22474487 -0.65465367 -0.65465367  0.75887436  0.74947325]
 [-0.81649658 -0.65465367  1.52752523 -1.71150388 -1.43817841]
 [-0.81649658  1.52752523 -0.65465367 -1.27555478 -0.89126549]
 [-0.81649658 -0.65465367  1.52752523 -0.11302384 -0.25320042]
 [-0.81649658  1.52752523 -0.65465367  0.17760889  0.        ]
 [ 1.22474487 -0.65465367 -0.65465367 -0.54897294 -0.52665688]
 [-0.81649658 -0.65465367  1.52752523  0.         -1.0735698 ]
 [ 1.22474487 -0.65465367 -0.65465367  1.34013983  1.38753832]
 [-0.81649658  1.52752523 -0.65465367  1.63077256  1.75214693]
 [ 1.22474487 -0.65465367 -0.65465367 -0.25834021  0.29371249]]
